language: node_js
node_js:
- "4.9"
- "5.12"
- "6.14"
- "7.10"
- "8.11"
- "9.11"
- "10.2"
- "10.13"
- "11.0"
sudo: false
cache:
  directories:
  - node_modules
before_script:
- npm install && npm install coveralls mocha-lcov-reporter --save-dev
script:
- npm run test:travis